package librarysystem;


import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author msand
 */
public class Addbook extends javax.swing.JFrame {

    /**
     * Creates new form addBook
     */
    public Addbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        yearText = new javax.swing.JTextField();
        publisherText = new javax.swing.JTextField();
        isbnText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();
        countryMenu = new javax.swing.JComboBox<>();
        languageMenu = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TITLE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("YEAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PUBLISHER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LANGUAGE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COUNTRY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, -1));

        yearText.setBackground(new java.awt.Color(0, 0, 0));
        yearText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        yearText.setForeground(new java.awt.Color(255, 255, 255));
        yearText.setSelectionColor(new java.awt.Color(255, 0, 51));
        yearText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTextKeyTyped(evt);
            }
        });
        getContentPane().add(yearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

        publisherText.setBackground(new java.awt.Color(0, 0, 0));
        publisherText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        publisherText.setForeground(new java.awt.Color(255, 255, 255));
        publisherText.setSelectionColor(new java.awt.Color(255, 0, 51));
        getContentPane().add(publisherText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 280, 30));

        isbnText.setBackground(new java.awt.Color(0, 0, 0));
        isbnText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        isbnText.setForeground(new java.awt.Color(255, 255, 255));
        isbnText.setSelectionColor(new java.awt.Color(255, 0, 51));
        isbnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextActionPerformed(evt);
            }
        });
        isbnText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                isbnTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isbnTextKeyTyped(evt);
            }
        });
        getContentPane().add(isbnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, 30));

        titleText.setBackground(new java.awt.Color(0, 0, 0));
        titleText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setSelectionColor(new java.awt.Color(255, 0, 51));
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 280, 30));

        countryMenu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        countryMenu.setForeground(new java.awt.Color(255, 255, 255));
        countryMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "United States", "New Zealand", "United Kingdom", "Canada", "Japan", "Germany", "Switzerland", "Australia", "Sri Lanka" }));
        getContentPane().add(countryMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 160, -1));

        languageMenu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        languageMenu.setForeground(new java.awt.Color(255, 255, 255));
        languageMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "English", "Tamil", "Sinhala", "Hindi", "Spanish", "French", "Arabic", "Bengali", "Russian", "Portuguese", "Indonesian" }));
        getContentPane().add(languageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, -1));

        add.setBackground(new java.awt.Color(51, 51, 51));
        add.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 110, -1));

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        exit.setText("RESET");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, -1));

        exit1.setBackground(new java.awt.Color(51, 51, 51));
        exit1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 100, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NcJJfou.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        setSize(new java.awt.Dimension(728, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        isbnText.setText("");
        titleText.setText("");
        yearText.setText("");
        publisherText.setText("");
        languageMenu.removeAllItems();
        countryMenu.removeAllItems();
    }//GEN-LAST:event_exitActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String isbn = isbnText.getText();
        String title = titleText.getText();
        String year = yearText.getText();
        String publisher = publisherText.getText();
        String language = languageMenu.getSelectedItem().toString();
        String country = countryMenu.getSelectedItem().toString();
        
        if(isbn.equals("")|title.equals("")|year.equals("")|publisher.equals("")|language.equals("SELECT")|country.equals("SELECT")){
            JOptionPane.showMessageDialog(null, "All Fields are Mandatory");
        }else{
        try {
            Connection con = DbConnection.getCon();
            String query = "INSERT INTO `books`(`isbn`, `title`, `year`, `publisher`, `language`, `country`) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, isbn);
            pst.setString(2, title);
            pst.setString(3, year);
            pst.setString(4, publisher);
            pst.setString(5, languageMenu.getSelectedItem().toString());
            pst.setString(6, countryMenu.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Successfully");
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Record Already Available");
        }
        }
    }//GEN-LAST:event_addActionPerformed

    private void isbnTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnTextKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            isbnText.setEditable(false);
        }else{
            isbnText.setEditable(true);
        }
    }//GEN-LAST:event_isbnTextKeyPressed

    private void isbnTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnTextKeyTyped
        if(isbnText.getText().length()>=12) {  
         evt.consume();
         
        }
    }//GEN-LAST:event_isbnTextKeyTyped

    private void yearTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTextKeyTyped
        if(yearText.getText().length()>=4) {  
         evt.consume();
        }
    }//GEN-LAST:event_yearTextKeyTyped

    private void yearTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTextKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            yearText.setEditable(false);
        }else{
            yearText.setEditable(true);
        }
    }//GEN-LAST:event_yearTextKeyPressed

    private void isbnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> countryMenu;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JTextField isbnText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> languageMenu;
    private javax.swing.JTextField publisherText;
    private javax.swing.JTextField titleText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables

    private static class ResultSet {

        public ResultSet() {
        }
    }
}
