package librarysystem;

import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author msand
 */
public class Addmember extends javax.swing.JFrame {

    /**
     * Creates new form addMembers
     */
    public Addmember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        contactText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("contact");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("birthday");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("address");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, -1));

        idText.setBackground(new java.awt.Color(0, 0, 0));
        idText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 255, 255));
        idText.setSelectionColor(new java.awt.Color(255, 0, 51));
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextKeyTyped(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 140, 30));

        nameText.setBackground(new java.awt.Color(0, 0, 0));
        nameText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setSelectionColor(new java.awt.Color(255, 0, 51));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 240, 30));

        contactText.setBackground(new java.awt.Color(0, 0, 0));
        contactText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        contactText.setForeground(new java.awt.Color(255, 255, 255));
        contactText.setSelectionColor(new java.awt.Color(255, 0, 51));
        contactText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTextKeyTyped(evt);
            }
        });
        getContentPane().add(contactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 30));

        emailText.setBackground(new java.awt.Color(0, 0, 0));
        emailText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        emailText.setSelectionColor(new java.awt.Color(255, 0, 51));
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 240, 30));

        addressText.setBackground(new java.awt.Color(0, 0, 0));
        addressText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        addressText.setForeground(new java.awt.Color(255, 255, 255));
        addressText.setSelectionColor(new java.awt.Color(255, 0, 51));
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 310, 30));

        add.setBackground(new java.awt.Color(51, 51, 51));
        add.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 110, -1));

        exit1.setBackground(new java.awt.Color(51, 51, 51));
        exit1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 100, -1));

        dateChooser.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 30));

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        exit.setText("RESET");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 100, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NcJJfou.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        setSize(new java.awt.Dimension(728, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         String id = idText.getText();
         String name = nameText.getText();
         String contact = contactText.getText();
         String birthday = ((JTextField)dateChooser.getDateEditor().getUiComponent()).getText();        
         String email = emailText.getText();
         String address =addressText.getText();
         
        if(id.equals("")|name.equals("")|contact.equals("")|birthday.equals("")|email.equals("")|address.equals("")){
            JOptionPane.showMessageDialog(null, "All Fields are Mandatory");
        }else{
            try {
                java.sql.Connection con = DbConnection.getCon();
                String query = "INSERT INTO `members`(`id`, `name`, `contact`, `birthday`, `email`, `address`) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, id);
                pst.setString(2, name);
                pst.setString(3, contact);
                pst.setString(4, birthday);
                pst.setString(5, email);
                pst.setString(6, address);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Record Already Available");
            }
            }
    }//GEN-LAST:event_addActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exit1ActionPerformed

    private void contactTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTextKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            contactText.setEditable(false);
        }else{
            contactText.setEditable(true);
        }
    }//GEN-LAST:event_contactTextKeyPressed

    private void contactTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTextKeyTyped
        if(contactText.getText().length()>=10) {  
         evt.consume();
        }
    }//GEN-LAST:event_contactTextKeyTyped

    private void idTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            idText.setEditable(false);
        }else{
            idText.setEditable(true);
        }
    }//GEN-LAST:event_idTextKeyPressed

    private void idTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyTyped
        if(idText.getText().length()>=10) {  
         evt.consume();
        }
    }//GEN-LAST:event_idTextKeyTyped

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        idText.setText("");
        nameText.setText("");
        contactText.setText("");
        dateChooser.setDate(null);
        emailText.setText("");
        addressText.setText("");
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel background;
    private javax.swing.JTextField contactText;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables
}
