package librarysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author msand
 */
public class Returnbook extends javax.swing.JFrame {

    /**
     * Creates new form returnBook
     */
    public Returnbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titleText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        isbnText = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TITLE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("return date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, -1));

        titleText.setBackground(new java.awt.Color(0, 0, 0));
        titleText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setSelectionColor(new java.awt.Color(255, 0, 51));
        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });
        getContentPane().add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 230, 30));

        idText.setBackground(new java.awt.Color(0, 0, 0));
        idText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 255, 255));
        idText.setSelectionColor(new java.awt.Color(255, 0, 51));
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextKeyTyped(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, 30));

        nameText.setBackground(new java.awt.Color(0, 0, 0));
        nameText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setSelectionColor(new java.awt.Color(255, 0, 51));
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 240, 30));

        isbnText.setBackground(new java.awt.Color(0, 0, 0));
        isbnText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        isbnText.setForeground(new java.awt.Color(255, 255, 255));
        isbnText.setSelectionColor(new java.awt.Color(255, 0, 51));
        isbnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextActionPerformed(evt);
            }
        });
        isbnText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                isbnTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isbnTextKeyTyped(evt);
            }
        });
        getContentPane().add(isbnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 110, 30));

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/returnbook.png"))); // NOI18N
        search.setText("RETURN");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        exit1.setBackground(new java.awt.Color(51, 51, 51));
        exit1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 100, -1));

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        exit.setText("RESET");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, -1));

        dateChooser.setBackground(new java.awt.Color(0, 0, 0));
        dateChooser.setForeground(new java.awt.Color(255, 255, 255));
        dateChooser.setDateFormatString("yyyy-MM-dd\n");
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 150, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NcJJfou.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        setSize(new java.awt.Dimension(728, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void isbnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exit1ActionPerformed

    private void isbnTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnTextKeyPressed
         char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            isbnText.setEditable(false);
        }else{
            isbnText.setEditable(true);
        }
    }//GEN-LAST:event_isbnTextKeyPressed

    private void isbnTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnTextKeyTyped
         if(isbnText.getText().length()>=12) {  
         evt.consume();
         
        }
    }//GEN-LAST:event_isbnTextKeyTyped

    private void idTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyTyped
         if(idText.getText().length()>=10) {  
         evt.consume();
         
        }
    }//GEN-LAST:event_idTextKeyTyped

    private void idTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyPressed
         char c = evt.getKeyChar();
         if(Character.isLetter(c)){
            idText.setEditable(false);
         }else{
            idText.setEditable(true);
        }
    }//GEN-LAST:event_idTextKeyPressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String isbn = isbnText.getText();
        String title = titleText.getText();
        String id = idText.getText();
        String name = nameText.getText();
        String date = ((JTextField)dateChooser.getDateEditor().getUiComponent()).getText();
        
        if(isbn.equals("")|title.equals("")|id.equals("")|name.equals("")|date.equals("")){
            JOptionPane.showMessageDialog(null, "All Fields are Mandatory");
        }else{
            try {
                Connection con = DbConnection.getCon();
                String query = "INSERT INTO `returns`(`isbn`, `title`, `id`, `name`, `date`) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, isbn);
                pst.setString(2, title);
                pst.setString(3, id);
                pst.setString(4, name);
                pst.setString(5, date);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Record Already Available");
            }
            }
    }//GEN-LAST:event_searchActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        isbnText.setText("");
        titleText.setText("");
        idText.setText("");
        nameText.setText("");
        dateChooser.setDate(null);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField isbnText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton search;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables
}
